formatter: markdown

output:
  file: README.md
  mode: inject

recursive:
  enabled: true
  path: .

settings:
  hide-empty: true

  # Avoid reading locked version from running validate
  lockfile: false
